export const ROUTES = {
    AUTH: '/auth',
    REGISTRATION: 'registration',
    MAIN: '/main',
    RESULT: '/result',
    ERROR_LOGIN: 'error-login',
    SUCCESS_REGISTRATION: 'success',
    ERROR_USER_EXIST: 'error-user-exist',
    ERROR_REGISTRATION: 'error',
} as const;

export const COMPOUND_ROUTES = {
    AUTH_REGISTRATION: `${ROUTES.AUTH}/${ROUTES.REGISTRATION}`,
    RESULT_ERROR_LOGIN: `${ROUTES.RESULT}/${ROUTES.ERROR_LOGIN}`,
    RESULT_SUCCESS_REGISTRATION: `${ROUTES.RESULT}/${ROUTES.SUCCESS_REGISTRATION}`,
    RESULT_ERROR_USER_EXIST: `${ROUTES.RESULT}/${ROUTES.ERROR_USER_EXIST}`,
    RESULT_ERROR_REGISTRATION: `${ROUTES.RESULT}/${ROUTES.ERROR_REGISTRATION}`,
} as const;
